- name: play1
  hosts: local
  connection: local
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "message from task1"

- name: play1
  hosts: local
  connection: local
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "message from task2"
      