- name: Variable
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    duration: 120HRS
    Trainer: Siva
  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "I am doing {{COURSE}} and duration was {{duration}}"
    - name: print the variables
      ansible.builtin.debug:
      vars:
         Trainer: Ajay
        msg: "I am doing {{COURSE}} and duration was {{duration}}, the trainer was {{Trainer}}"

- name: Variable
  hosts: local
  connection: local
  tasks:
    - name: print the variables
      ansible.builtin.debug:
      vars:
        COURSE: "Devops with AWS"
        duration: 100HRS
        msg: "I am doing {{COURSE}} and duration was {{duration}}, the trainer was {{Trainer}}"
