- name: ansible
  hosts: local
  connection: local
  vars_prompt:
  - name: Course
    prompt: Please enter the course name
  - name: duration
    prompt: Enter duration period
  - name: Username
    prompt: Enter username
  - name: password
    prompt: Enter password
  tasks:
  - name: Enter the variables
    ansible.builtin.debug:
      msg:"I am doing {{COURSE}} and duration was {{duration}}, the trainer was {{Username}}"