- name: Variable
  hosts: local
  connection: local
  
  tasks:
    - name: print the variables
      ansible.builtin.debug:
           msg: "I am doing {{COURSE}} and duration was {{duration}}, the trainer was {{Trainer}}"
